---

my-git:
  image: amitvashist7/myapache-acc:v3
  ports:
    - '8093:80'



my-test:
  image: amitvashist7/myapache-acc:v2
  ports:
    - '8092:80'



my-prod:
  image: amitvashist7/myapache-acc:v1
  ports:
    - '8091:80'
